site_name: ionscale

# Remove the GitHub repository link from the top-right corner
# repo_name: jsiebens/ionscale
# repo_url: https://github.com/jsiebens/ionscale
# edit_uri: ""

nav:
  - Overview:
      - Introduction: index.md
      - Supported Features: overview/features.md
  - Installation:
      - Installation: ./installation/index.md
      - Linux installation: ./installation/linux.md
      - Docker installation: ./installation/docker.md
  - Configuration:
      - Configuration: ./configuration/index.md
      - DERP: ./configuration/derp.md
      - OIDC: ./configuration/auth-oidc.md
      - DNS providers: ./configuration/dns-providers.md
  - Getting started:
      - Getting started: ./getting-started/index.md
      - Creating a tailnet: ./getting-started/tailnet.md
      - IAM Policies: ./getting-started/iam-policies.md
      - ACL Policies: ./getting-started/acl-policies.md

theme:
  name: material
  custom_dir: overrides
  
  # Custom stylesheets
  extra_css:
    - stylesheets/extra.css
  
  # Explicitly disable the logo to show only the site name
  #logo: ""
  favicon: assets/favicon.png

  # Enhanced color scheme
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Lato
    code: Roboto Mono

  features:
    # Navigation
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top         # Back-to-top button
    - navigation.footer      # Footer with previous/next links
    
    # Content
    - content.code.copy      # Add copy button to code blocks
    - content.code.annotate  # Allow code annotations
    - content.tabs.link      # Sync all tabs with the same label
    
    # Search
    - search.highlight
    - search.share
    - search.suggest
    
    # Table of contents
    - toc.follow
  
  # Hide the table of contents on the navigation
  toc_depth: 0

  include_search_page: false
  search_index_only: true

  language: en

markdown_extensions:
  # Admonitions and callouts
  - admonition
  - pymdownx.details
  
  # Code blocks with syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  
  # Code annotations
  - pymdownx.snippets
  
  # Tabbed content
  - pymdownx.tabbed:
      alternate_style: true
  
  # Content tabs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Better formatting options
  - attr_list             # Add HTML attributes and CSS classes
  - def_list              # Definition lists
  - md_in_html            # Markdown within HTML
  - tables                # Tables
  - footnotes             # Footnotes
  
  # Typography improvements
  - pymdownx.critic       # Track changes
  - pymdownx.caret        # Superscript/subscript
  - pymdownx.mark         # Highlighting
  - pymdownx.tilde        # Strikethrough
  - pymdownx.smartsymbols # Smart symbols (arrows, fractions)

extra:
  # Page status annotations
  status:
    new: Recently added
    deprecated: No longer supported
    beta: Currently in beta
  
  # Enhanced social cards
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jsiebens/ionscale
    - icon: fontawesome/brands/docker
      link: https://github.com/jsiebens/ionscale/pkgs/container/ionscale
  
  # Page customization
#  version:
#    provider: mike
  
  # Footer customization
  generator: false  # Hide "Made with Material for MkDocs"
  
  # Analytics (existing)
  analytics:
    provider: custom